### ISSUE TITLE
Select Red LEDs 

### ISSUE THREAD

**Issue by jalcok1** [jalcok1/capstone#10]
We need 8 of them

**Comment by SethMWard** [comment]
Any of these will do
http://www.digikey.com/product-detail/en/LH%20R974-LP-1/475-1415-1-ND/1802604

http://www.digikey.com/product-detail/en/LS%20Q976-NR-1/475-2512-1-ND/1802639

lower amp
http://www.digikey.com/product-detail/en/LS%20M67K-H2L1-1-Z/475-2510-1-ND/1802637

**Comment by SethMWard** [comment]
Chose the 2nd option
http://www.digikey.com/product-detail/en/LS%20Q976-NR-1/475-2512-1-ND/1802639
closing
