### ISSUE TITLE
Find CAN a can transceiver

### ISSUE THREAD

**Issue by jalcok1** [jalcok1/capstone#14]

**Comment by SethMWard** [comment]
Will keep researching this. In the meantime I have ordered a sample for this transceiver
https://store.ti.com/SN65HVD230DR-33V-CAN-Transceiver-with-Standby-Mode-P18464.aspx

**Comment by SethMWard** [comment]
Questions we have about this are:
1) Operating Temperature 
2) Half or Full Duplex
3) Transmission Hysteresis - Do we want this lower or higher?

**Comment by SethMWard** [comment]
Found one, made the library and pushed the package
