### ISSUE TITLE
Research components/Work on BOM

### ISSUE THREAD

**Issue by SethMWard** [jalcok1/capstone#3]
Start creating bill of materials

**Comment by jalcok1** [comment]
Started a list of possible parts:

https://github.com/jalcok1/capstone/blob/master/hardware/component_selection.csv?raw=true

At the bottom of each sheet there is a link to digikey, this will be useful for quickly selecting data sheets actual component selection.

**Comment by jalcok1** [comment]
At this time the BOM is current and all known components that will be used are entered into the spreadsheet.
