### ISSUE TITLE
Find SPI driven DAC 

### ISSUE THREAD

**Issue by jalcok1** [jalcok1/capstone#9]
12-bit resolution
0-3.3V output
$5.00 Max cost

Looks like we need to figure out how to hook it up to USART

**Comment by SethMWard** [comment]
Looks like we just need RX, TX, and the Clock. NSS can be any GPIO.
http://www.ue.pwr.wroc.pl/systemy_rt/RTE9.pdf

**Comment by jalcok1** [comment]
Found a DAC chip with 2 outputs.  MCP4922, 12bit DAC.  I created library and added it to the schematic.
